name: Update and Sync Snowflake Database

on:
  push:
    branches:
      - main

jobs:
  update_and_sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl snowflake-connector-python

    - name: Update Excel File
      run: python update_excel.py

    - name: Sync with Snowflake
      env:
        SNOWFLAKE_USER: ${{ secrets.USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.PASSWORD }}
        SNOWFLAKE_ACCOUNT: ${{ secrets.ACCOUNT }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.WAREHOUSE }}
        SNOWFLAKE_DATABASE: ${{ secrets.DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SCHEMA }}
        SNOWFLAKE_ROLE: ${{ secrets.ROLE }}
      run: python update_snowflake.py

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Updated data in Excel and synced with Snowflake"
        git push
